spring.application.name=audio-wave
jwt.secret=${JWT_SECRET:JWT_SECRET}
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/audiowave_db
spring.datasource.username=postgres
spring.datasource.password=DCD453145
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.flyway=false
#ADMIN
admin.email=eduardoteleyos@gmail.com
admin.password=Fuck1n6@dm1n15tr@t0r
admin.name=Administrator
logging.level.org.springframework.security=DEBUG
